docs: update installation instructions
cloudflare/wildebeest pull request #155
Opened 2023-01-24 19:45 UTC by nodomain

Partially fixes #149

2023-01-30 14:36 UTC, xtuc requested changes

2023-01-30 14:36 UTC, xtuc commented on README.md
> +_Note: the API permissions are missing several scopes, see https://github.com/cloudflare/wildebeest/issues/149#issuecomment-1402125492 for details._
This note isn't needed anymore. Can you please remove?

2023-02-11 16:15 UTC, 53jk1 approved these changes

2023-02-13 17:05 UTC, xtuc commented
Since the README has been rewritten is that change still needed?

2023-02-15 10:53 UTC, celso commented
We revamped the docs.

2023-02-15 10:53 UTC, closed without merging